/* Colores 0xFF & {} */

#define COL_SERVER      "{E3BD6B}" // Dorado
#define COLOR_SERVER     (0xE3BD6BFF)

#define COL_TITLE       "{CCCCCC}" // Blanco grisáceo
#define COLOR_TITLE     (0xCCCCCCFF)

#define COL_CONTENT     "{D9D9D9}" // Blanco un poco grisáceo
#define COLOR_CONTENT   (0xD9D9D9FF)

#define COL_CONTENT_TWO "{A9C4E4}" // Color de SA:MP

#define COL_WHITE 		"{FFFFFF}" // Blanco
#define COLOR_WHITE 	(0xFFFFFFFF)

#define COL_WHITE_TWO   "{D9D9D9}" // Blanco un poco grisáceo
#define COLOR_WHITE_TWO (0xD9D9D9FF)

#define COL_TOMATO 		"{F05C41}" // SendWarningMessage
#define COLOR_TOMATO 	(0xF05C41FF)

#define COL_LIGHTRED 	"{FF6347}"
#define COLOR_LIGHTRED 	(0xFF6347AA)

#define COL_ADMIN 	    "{EE6C68}" // SendAdminMessage
#define COLOR_ADMIN     (0xEE6C68FF)

#define COL_ADMIN_TWO   "{DABB3E}"
#define COLOR_ADMIN_TWO (0xDABB3EAA)

#define COL_ORANGE 		"{EA8215}" // Naranja
#define COLOR_ORANGE    (0xEA821500)

#define COL_YELLOW 		"{FFDD00}" // Amarillo
#define COLOR_YELLOW 	(0xFFDD00FF)

#define COLOR_YELLOW_TWO (0xF5DEB3AA) // Amarillo gastadísimo
#define COL_YELLOW_TWO  "{F5DEB3}"

#define COL_GREEN 		"{9AC337}" // Verde
#define COLOR_GREEN 	(0x9AC337FF)

#define COL_GREEN_TWO 	"{81A42E}" // Verde más oscuro
#define COLOR_GREEN_TWO (0x81A42EFF)

#define COLOR_PURPLE    (0xD0AEEBFF) // Púrpura
#define COL_PURPLE      "{D0AEEB}"

#define COLOR_DO        (0x9AC337FF) // Verde de toda la vida
#define COL_DO          "{9AC337}"

#define COL_DEFAULT 	"{A9C4E4}" // Color de SA:MP
#define COLOR_DEFAULT 	(0xA9C4E4FF)

#define COL_GREY        "{B0B0B0}" // Gris
#define COLOR_GREY      (0xB0B0B0FF)

#define COL_BLACK       "{000000}" // Negro
#define COLOR_BLACK     (0x000000FF)

#define COL_3DTEXT  	"{E6DE40}" // Dorado (C. P.)
#define COLOR_3DTEXT   	(0xE6DE40BB)

#define COLOR_CHAT_0	(0xE6E6E699)
#define COL_CHAT_0      "{E6E6E6}"

#define COLOR_CHAT_1 	(0xC8C8C8C8)
#define COL_CHAT_1      "{C8C8C8}"

#define COLOR_CHAT_2 	(0xAAAAAAAA)
#define COL_CHAT_2      "{AAAAAA}"

#define COLOR_CHAT_3 	(0x8C8C8C8C)
#define COL_CHAT_3      "{8C8C8C}"

#define COLOR_CHAT_4 	(0x6E6E6E6E)
#define COL_CHAT_4      "{6E6E6E}"

#define COLOR_PIEL      (0xE1B181FF)
#define COL_PIEL        "{E1B181}"

#define COLOR_CYAN      (0x56B8D9FF)
#define COL_CYAN        "{56B8D9}"

#define COLOR_DOUBTS    (0xE1D398FF) // Amarillo cosquín
#define COLOR_DOUBTS_TWO (0xB9AC76FF) // Más oscuro para ShowPlayerBox
#define COL_DOUBTS      "{E1D398}"

#define COLOR_REPORTS   (0xE19898FF) // Rojo 2.45
#define COLOR_REPORTS_TWO (0xB97373FF) // Más oscuro para ShowPlayerBox
#define COL_REPORTS     "{E19898}"

#define COLOR_TEXTDRAW  (0xFFFFFF88)
#define COLOR_TRANSPARENCE (0x0000000)
